import { Inter } from "next/font/google"
import Header from "../components/./header"
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";


const inter = Inter({ subsets: ['latin'] })

export const Metadata = {
  title: "core-drive drives",
  description: "Find your dream car",
};


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${inter.className}`}
        >
          <Header />
          <main className="min-h-screen">
            {children}
          </main>
          <footer className="flex justify-center items-center bg-gray-950 py-1.5">
            <div className="container flex flex-col mx-auto">
              <p className="text-center text-white text-2xl font-semibold">created with love by peter</p>
              <p className="text-center text-white text-3xl font-bold hover:text-gray-300">peterslap67@gmail.com</p>
            </div>
          </footer>
        </body>
      </html>
    </ClerkProvider>
  );
}
